import {
    ChevronLeft,
    ChevronRight,
    Command,
    Loader2,
    Plus,
    Settings,
    Box,
    X,
    Home,
    Settings2,
    History,
    Play,
    Pause,
    FolderOpen,
    CreditCard,
    User,
    ArrowRight,
    Grid,
    Minus,
    RotateCcw,
    UsersRound,
    Wrench,
    Undo2,
    Pencil,
    Trash,
    AlertTriangle,
    Search,
    FolderKanban,
    ListMinus,
    Save,
    Group,
    Link,
} from 'lucide-react';

export const Icons = {
    billing: CreditCard,
    arrowRight: ArrowRight,
    setting: Settings2,
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    folder: FolderOpen,
    settings: Settings,
    add: Plus,
    engine: Box,
    dashboard: Home,
    history: History,
    play: Play,
    pause: Pause,
    users: User,
    usergroup: UsersRound,
    grid: Grid,
    minus: Minus,
    rotate: RotateCcw,
    wrench: Wrench,
    back: Undo2,
    edit: Pencil,
    delete: Trash,
    alert: AlertTriangle,
    search: Search,
    projects: FolderKanban,
    list: ListMinus,
    save: Save,
    projectGroups: Group,
    undo: Undo2,
    link: Link,
};
